import type { Warehouse, Product } from './types'

// database
export const warehouses: Warehouse[] = [
    {
        code: 'BLR-A',
        name: 'Bengaluru Alpha',
        city: 'Bengaluru',
        country: 'India',
    },
    { code: 'PNQ-C', name: 'Pune Charlie', city: 'Pune', country: 'India' },
    { code: 'DEL-B', name: 'Delhi Bravo', city: 'New Delhi', country: 'India' },
]

export let products: Product[] = [
    {
        id: 'P-1001',
        name: '12mm Hex Bolt',
        sku: 'HEX-12-100',
        warehouse: 'BLR-A',
        stock: 180,
        demand: 120,
    },
    {
        id: 'P-1002',
        name: 'Steel Washer',
        sku: 'WSR-08-500',
        warehouse: 'BLR-A',
        stock: 50,
        demand: 80,
    },
    {
        id: 'P-1003',
        name: 'M8 Nut',
        sku: 'NUT-08-200',
        warehouse: 'PNQ-C',
        stock: 80,
        demand: 80,
    },
    {
        id: 'P-1004',
        name: 'Bearing 608ZZ',
        sku: 'BRG-608-50',
        warehouse: 'DEL-B',
        stock: 24,
        demand: 120,
    },
    {
        id: 'P-1005',
        name: 'Socket Head Cap Screw',
        sku: 'SHC-10-75',
        warehouse: 'BLR-A',
        stock: 95,
        demand: 60,
    },
    {
        id: 'P-1006',
        name: 'Flat Head Screw',
        sku: 'FHS-06-40',
        warehouse: 'PNQ-C',
        stock: 45,
        demand: 90,
    },
    {
        id: 'P-1007',
        name: 'Lock Washer',
        sku: 'LWS-10-300',
        warehouse: 'DEL-B',
        stock: 150,
        demand: 150,
    },
    {
        id: 'P-1008',
        name: 'Threaded Rod',
        sku: 'THR-12-1000',
        warehouse: 'BLR-A',
        stock: 30,
        demand: 75,
    },
    {
        id: 'P-1009',
        name: 'Wing Nut',
        sku: 'WNG-08-100',
        warehouse: 'PNQ-C',
        stock: 200,
        demand: 120,
    },
    {
        id: 'P-1010',
        name: 'Ball Bearing 6200',
        sku: 'BBR-6200-25',
        warehouse: 'DEL-B',
        stock: 18,
        demand: 45,
    },
    {
        id: 'P-1011',
        name: 'Carriage Bolt',
        sku: 'CBT-10-80',
        warehouse: 'BLR-A',
        stock: 110,
        demand: 110,
    },
    {
        id: 'P-1012',
        name: 'Spring Washer',
        sku: 'SPW-12-250',
        warehouse: 'PNQ-C',
        stock: 75,
        demand: 120,
    },
    {
        id: 'P-1013',
        name: 'Thumb Screw',
        sku: 'THS-08-60',
        warehouse: 'DEL-B',
        stock: 160,
        demand: 90,
    },
    {
        id: 'P-1014',
        name: 'Hex Nut M10',
        sku: 'HNT-10-400',
        warehouse: 'BLR-A',
        stock: 85,
        demand: 140,
    },
    {
        id: 'P-1015',
        name: 'Flange Bearing',
        sku: 'FBR-12-30',
        warehouse: 'PNQ-C',
        stock: 42,
        demand: 42,
    },
    {
        id: 'P-1016',
        name: 'Set Screw',
        sku: 'SSC-06-120',
        warehouse: 'DEL-B',
        stock: 220,
        demand: 180,
    },
    {
        id: 'P-1017',
        name: 'Eye Bolt',
        sku: 'EBT-14-50',
        warehouse: 'BLR-A',
        stock: 35,
        demand: 70,
    },
    {
        id: 'P-1018',
        name: 'Nylon Washer',
        sku: 'NYW-08-200',
        warehouse: 'PNQ-C',
        stock: 180,
        demand: 100,
    },
    {
        id: 'P-1019',
        name: 'Roller Bearing',
        sku: 'RBR-6201-40',
        warehouse: 'DEL-B',
        stock: 28,
        demand: 85,
    },
    {
        id: 'P-1020',
        name: 'Machine Screw',
        sku: 'MSC-04-300',
        warehouse: 'BLR-A',
        stock: 125,
        demand: 125,
    },
    {
        id: 'P-1021',
        name: 'Coupling Nut',
        sku: 'CPN-12-80',
        warehouse: 'PNQ-C',
        stock: 65,
        demand: 110,
    },
    {
        id: 'P-1022',
        name: 'Thrust Bearing',
        sku: 'TBR-51100-15',
        warehouse: 'DEL-B',
        stock: 12,
        demand: 35,
    },
    {
        id: 'P-1023',
        name: 'Pan Head Screw',
        sku: 'PHS-05-250',
        warehouse: 'BLR-A',
        stock: 190,
        demand: 140,
    },
    {
        id: 'P-1024',
        name: 'Rubber Washer',
        sku: 'RUW-10-150',
        warehouse: 'PNQ-C',
        stock: 95,
        demand: 95,
    },
]
